# Generated by Django 5.0.2 on 2025-12-02 17:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Κωδικός')),
                ('barcode', models.CharField(blank=True, max_length=200, null=True, verbose_name='QR/Bar Code')),
                ('name', models.CharField(max_length=200, verbose_name='Όνομα')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Τιμή')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Περιγραφή')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ποσότητα')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
            ],
            options={
                'verbose_name': 'Προϊόν',
                'verbose_name_plural': 'Προϊόντα',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ποσότητα')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Τιμή Πώλησης')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Συνολικό Ποσό')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Πώλησης')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Προϊόν')),
            ],
            options={
                'verbose_name': 'Πώληση',
                'verbose_name_plural': 'Πωλήσεις',
                'ordering': ['-created_at'],
            },
        ),
    ]
