# Generated by Django 5.0.2 on 2025-12-03 19:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Όνομα Απογραφής')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Περιγραφή')),
                ('status', models.CharField(choices=[('draft', 'Σε Εξέλιξη'), ('completed', 'Ολοκληρωμένη'), ('applied', 'Εφαρμοσμένη')], default='draft', max_length=20, verbose_name='Κατάσταση')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Ολοκλήρωσης')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
            ],
            options={
                'verbose_name': 'Απογραφή',
                'verbose_name_plural': 'Απογραφές',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Μετρημένη Ποσότητα')),
                ('system_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ποσότητα Συστήματος')),
                ('difference', models.IntegerField(default=0, verbose_name='Διαφορά')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Καταχώρησης')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Καταχωρήθηκε από')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='warehouse.inventory', verbose_name='Απογραφή')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Προϊόν')),
            ],
            options={
                'verbose_name': 'Προϊόν Απογραφής',
                'verbose_name_plural': 'Προϊόντα Απογραφής',
                'ordering': ['product__name'],
                'unique_together': {('inventory', 'product')},
            },
        ),
    ]
