# Generated by Django 5.0.2 on 2025-12-10 04:36

from django.db import migrations


def migrate_price_to_retail_price(apps, schema_editor):
    """Migrate existing price values to retail_price"""
    Product = apps.get_model('warehouse', 'Product')
    for product in Product.objects.all():
        if product.price and not product.retail_price:
            product.retail_price = product.price
            # Set wholesale_price to same value if not set
            if not product.wholesale_price:
                product.wholesale_price = product.price
            product.save()


def reverse_migrate(apps, schema_editor):
    """Reverse migration - move retail_price back to price"""
    Product = apps.get_model('warehouse', 'Product')
    for product in Product.objects.all():
        if product.retail_price and not product.price:
            product.price = product.retail_price
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_add_wholesale_retail_prices'),
    ]

    operations = [
        migrations.RunPython(migrate_price_to_retail_price, reverse_migrate),
    ]
