# Generated by Django 5.0.2 on 2025-12-10 04:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def set_defaults(apps, schema_editor):
    """Set default category and prices for existing products"""
    Product = apps.get_model('warehouse', 'Product')
    ProductCategory = apps.get_model('warehouse', 'ProductCategory')
    
    # Get or create a default category
    default_category = ProductCategory.objects.first()
    if not default_category:
        default_category = ProductCategory.objects.create(
            name='ΓΕΝΙΚΗ',
            description='Γενική κατηγορία προϊόντων'
        )
    
    # Set default category for products without category
    products_without_category = Product.objects.filter(category__isnull=True)
    products_without_category.update(category=default_category)
    
    # Set default prices for products without prices
    for product in Product.objects.all():
        if not product.retail_price:
            # Use old price if exists, otherwise set to 0.01
            product.retail_price = product.price if product.price else Decimal('0.01')
        if not product.wholesale_price:
            # Use retail_price if exists, otherwise set to 0.01
            product.wholesale_price = product.retail_price if product.retail_price else Decimal('0.01')
        product.save()


def reverse_set_defaults(apps, schema_editor):
    """Reverse migration - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_migrate_price_data'),
    ]

    operations = [
        migrations.RunPython(set_defaults, reverse_set_defaults),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='warehouse.productcategory', verbose_name='Κατηγορία'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Τιμή Πώλησης'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Χονδρική Τιμή'),
        ),
    ]
