# Generated by Django 5.0.2 on 2025-12-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_remove_auto_now_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Πώλησης'),
        ),
    ]
