# Generated by Django 5.0.2 on 2025-12-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_allow_null_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCodeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_code', models.IntegerField(default=-1, verbose_name='Τελευταίος Χρησιμοποιημένος Κωδικός')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
            ],
            options={
                'verbose_name': 'Μετρητής Κωδικών Προϊόντων',
                'verbose_name_plural': 'Μετρητής Κωδικών Προϊόντων',
            },
        ),
    ]
