# Generated by Django 5.0.2 on 2025-12-10 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_initialize_code_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Όριο Χαμηλού Αποθέματος')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
            ],
            options={
                'verbose_name': 'Ρυθμίσεις Αποθήκης',
                'verbose_name_plural': 'Ρυθμίσεις Αποθήκης',
            },
        ),
    ]
