# Generated by Django 5.0.2 on 2026-06-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_add_warehouse_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
