# Generated by Django 5.0.2 on 2026-06-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_remove_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='retail_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale_price',
        ),
    ]
