# Generated by Django 5.0.2 on 2026-06-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_remove_product_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
