# Generated by Django 5.0.2 on 2026-06-28 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_remove_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['product__name'], 'verbose_name': 'Υλικό Απογραφής', 'verbose_name_plural': 'Υλικά Απογραφής'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Υλικό', 'verbose_name_plural': 'Υλικά'},
        ),
        migrations.AlterModelOptions(
            name='productcodecounter',
            options={'verbose_name': 'Μετρητής Κωδικών Υλικών', 'verbose_name_plural': 'Μετρητής Κωδικών Υλικών'},
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Υλικό'),
        ),
    ]
