# Generated by Django 5.0.2 on 2026-06-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_rename_product_to_material_labels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
