# Generated by Django 5.0.2 on 2026-07-15 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Τίτλος εργασίας')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('scheduled_date', models.DateField(verbose_name='Ημερομηνία εκτέλεσης')),
                ('priority', models.CharField(choices=[('low', 'Χαμηλή'), ('medium', 'Μεσαία'), ('high', 'Υψηλή')], default='medium', max_length=10, verbose_name='Προτεραιότητα')),
                ('status', models.CharField(choices=[('pending', 'Εκκρεμεί'), ('in_progress', 'Σε εξέλιξη'), ('completed', 'Ολοκληρωμένη'), ('cancelled', 'Ακυρωμένη')], default='pending', max_length=20, verbose_name='Κατάσταση')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία ενημέρωσης')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ανάθεση σε')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
            ],
            options={
                'verbose_name': 'Προγραμματισμένη εργασία',
                'verbose_name_plural': 'Προγραμματισμένες εργασίες',
                'ordering': ['scheduled_date', '-priority', 'title'],
            },
        ),
    ]
