# Generated by Django 5.0.2 on 2026-07-24 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_in_progress_status'),
        ('products', '0013_task_stock_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtaskitem',
            name='reserved_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_reservations', to='products.productstock', verbose_name='Δεσμευμένο απόθεμα'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='scheduled_date',
            field=models.DateField(verbose_name='Επιθυμητή Ημερομηνία Ολοκλήρωσης'),
        ),
        migrations.AlterField(
            model_name='scheduledtaskitem',
            name='item_status',
            field=models.CharField(choices=[('under_work', 'Υπό κατασκευή'), ('reserved', 'Δεσμευμένο'), ('completed', 'Ολοκληρώθηκε')], default='under_work', max_length=20, verbose_name='Κατάσταση προϊόντος'),
        ),
    ]
