# Generated by Django 5.0.2 on 2026-07-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_task_stock_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtaskitem',
            name='item_status',
            field=models.CharField(choices=[('under_work', 'Υπό κατασκευή'), ('reserved', 'Δεσμευμένο'), ('completed', 'Ολοκληρώθηκε'), ('shipped', 'Έχει αποσταλεί')], default='under_work', max_length=20, verbose_name='Κατάσταση προϊόντος'),
        ),
    ]
