# Generated by Django 5.0.2 on 2026-07-25 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0013_task_stock_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationOfPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=30, unique=True, verbose_name='Αριθμός Δηλώσης')),
                ('source_document_type', models.CharField(choices=[('invoice', 'ΤΙΜΟΛΟΓΙΟ ΠΩΛΗΣΗΣ'), ('delivery', 'ΔΕΛΤΙΟ ΑΠΟΣΤΟΛΗΣ')], max_length=20, verbose_name='Τύπος παραστατικού')),
                ('source_document_number', models.CharField(max_length=50, verbose_name='Αριθμός παραστατικού')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dops_created', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_of_performance', to='products.finishedproduct', verbose_name='Προϊόν')),
            ],
            options={
                'verbose_name': 'Δήλωση Απόδοσης',
                'verbose_name_plural': 'Δηλώσεις Απόδοσης',
                'ordering': ['-created_at'],
            },
        ),
    ]
