# Generated by Django 5.0.2 on 2026-07-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='documents/dop/logo/', verbose_name='Λογότυπο')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Τελευταία ενημέρωση')),
            ],
            options={
                'verbose_name': 'Ρυθμίσεις Δηλώσης Απόδοσης',
                'verbose_name_plural': 'Ρυθμίσεις Δηλώσης Απόδοσης',
            },
        ),
    ]
