# Generated by Django 5.0.2 on 2026-07-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_dopsettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dopsettings',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='documents/dop/signature/', verbose_name='Υπογραφή'),
        ),
    ]
