# Generated by Django 5.0.2 on 2026-07-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_dopsettings_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='dopsettings',
            name='logo_as_watermark',
            field=models.BooleanField(default=False, verbose_name='Υδατογράφημα'),
        ),
    ]
