# Generated by Django 5.0.2 on 2026-07-25 11:31

from django.db import migrations, models


def remap_source_document_types(apps, schema_editor):
    DeclarationOfPerformance = apps.get_model('documents', 'DeclarationOfPerformance')
    DeclarationOfPerformance.objects.filter(source_document_type='invoice').update(
        source_document_type='invoice_delivery',
    )
    DeclarationOfPerformance.objects.filter(source_document_type='delivery').update(
        source_document_type='retail',
    )


def reverse_remap_source_document_types(apps, schema_editor):
    DeclarationOfPerformance = apps.get_model('documents', 'DeclarationOfPerformance')
    DeclarationOfPerformance.objects.filter(source_document_type='invoice_delivery').update(
        source_document_type='invoice',
    )
    DeclarationOfPerformance.objects.filter(source_document_type='retail').update(
        source_document_type='delivery',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_dopsettings_logo_watermark'),
    ]

    operations = [
        migrations.RunPython(remap_source_document_types, reverse_remap_source_document_types),
        migrations.AlterField(
            model_name='declarationofperformance',
            name='source_document_type',
            field=models.CharField(
                choices=[
                    ('invoice_delivery', 'ΤΙΜΟΛΟΓΙΟ - ΔΕΛΤΙΟ ΑΠΟΣΤΟΛΗΣ'),
                    ('retail', 'ΑΠΟΔΕΙΞΗ ΛΙΑΝΙΚΗΣ'),
                ],
                max_length=20,
                verbose_name='Τύπος παραστατικού',
            ),
        ),
    ]
