# Generated by Django 5.0.2 on 2026-07-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_update_source_document_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationofperformance',
            name='show_signature',
            field=models.BooleanField(default=True, verbose_name='Εμφάνιση Υπογραφής'),
        ),
    ]
