# Generated by Django 5.0.2 on 2026-07-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_dop_show_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='dopsettings',
            name='ce_mark',
            field=models.ImageField(blank=True, null=True, upload_to='documents/dop/ce/', verbose_name='Σήμανση CE'),
        ),
    ]
