# Generated by Django 5.0.2 on 2026-07-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_dopsettings_ce_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='dopsettings',
            name='header_company_activity',
            field=models.CharField(default='ΕΠΕΞΕΡΓΑΣΙΑ - ΕΜΠΟΡΙΑ ΥΑΛΟΠΙΝΑΚΩΝ', max_length=200, verbose_name='Δραστηριότητα κεφαλίδας'),
        ),
        migrations.AddField(
            model_name='dopsettings',
            name='header_company_details',
            field=models.TextField(default='Ελ. Βενιζέλου 40, Αμαλιάδα\nΤηλ. 26220 28686 · Κιν. 6977 240040\nEmail: info@tasosxristodoulopoulosglass.gr\nΑΦΜ: 043758710 · ΔΟΥ: Αμαλιάδας', verbose_name='Στοιχεία κεφαλίδας'),
        ),
        migrations.AddField(
            model_name='dopsettings',
            name='header_company_name',
            field=models.CharField(default='ΧΡΙΣΤΟΔΟΥΛΟΠΟΥΛΟΣ Γ. ΑΝΑΣΤΑΣΙΟΣ', max_length=200, verbose_name='Επωνυμία κεφαλίδας'),
        ),
    ]
