# Generated by Django 5.0.2 on 2026-07-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_dopsettings_header_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='dopsettings',
            name='section_1_label',
            field=models.TextField(default='1. Μοναδικός κωδικός ταυτοποίησης προϊόντος', verbose_name='Ενότητα 1 - Τίτλος'),
        ),
        migrations.AddField(
            model_name='dopsettings',
            name='section_2_label',
            field=models.TextField(default='2. Αριθμός τύπου, παρτίδας ή σειράς ή οποιοδήποτε άλλο στοιχείο επιτρέπει την ταυτοποίηση του προϊόντος του τομέα των δομικών κατασκευών, όπως προβλέπει', verbose_name='Ενότητα 2 - Τίτλος'),
        ),
        migrations.AddField(
            model_name='dopsettings',
            name='section_2_value',
            field=models.TextField(blank=True, default='', verbose_name='Ενότητα 2 - Κείμενο'),
        ),
        migrations.AddField(
            model_name='dopsettings',
            name='section_3_label',
            field=models.TextField(default='3. Προτεινόμενη χρήση ή χρήσεις του προϊόντος του τομέα δομικών κατασκευών, σύμφωνα με την ισχύουσα εναρμονισμένη τεχνική προδιαγραφή, όπως προβλέπεται από τον κατασκευαστή:', verbose_name='Ενότητα 3 - Τίτλος'),
        ),
        migrations.AddField(
            model_name='dopsettings',
            name='section_3_value',
            field=models.TextField(default='Διπλοί μονωτικοί υαλοπίνακες που πρόκειται να χρησιμοποιηθούν σε κτήρια και κατασκευαστικά έργα', verbose_name='Ενότητα 3 - Κείμενο'),
        ),
        migrations.AddField(
            model_name='dopsettings',
            name='section_4_label',
            field=models.TextField(default='4. Όνομα, εμπορική επωνυμία ή κατατεθέν σήμα και διεύθυνση επικοινωνίας του κατασκευαστή, όπως προβλέπεται στο άρθρο 11, παράγραφος 5:', verbose_name='Ενότητα 4 - Τίτλος'),
        ),
        migrations.AddField(
            model_name='dopsettings',
            name='section_4_value',
            field=models.TextField(default='ΧΡΙΣΤΟΔΟΥΛΟΠΟΥΛΟΣ Γ. ΑΝΑΣΤΑΣΙΟΣ, ΕΛ. ΒΕΝΙΖΕΛΟΥ 40, ΑΜΑΛΙΑΔΑ', verbose_name='Ενότητα 4 - Κείμενο'),
        ),
        migrations.AddField(
            model_name='dopsettings',
            name='section_5_label',
            field=models.TextField(default='5. Όπου εφαρμόζεται, όνομα και διεύθυνση επικοινωνίας του εξουσιοδοτημένου αντιπροσώπου, η εντολή του οποίου καλύπτει τα καθήκοντα που προβλέπονται στο άρθρο 12 παρ. 2:', verbose_name='Ενότητα 5 - Τίτλος'),
        ),
        migrations.AddField(
            model_name='dopsettings',
            name='section_5_value',
            field=models.TextField(default='Δεν εφαρμόζεται', verbose_name='Ενότητα 5 - Κείμενο'),
        ),
        migrations.AddField(
            model_name='dopsettings',
            name='section_6_label',
            field=models.TextField(default='6. Σύστημα ή συστήματα αξιολόγησης και επαλήθευσης της σταθερότητας της απόδοσης του προϊόντος του τομέα των δομικών κατασκευών όπως καθορίζεται στο παράρτημα V:', verbose_name='Ενότητα 6 - Τίτλος'),
        ),
        migrations.AddField(
            model_name='dopsettings',
            name='section_6_value',
            field=models.TextField(default='Σύστημα 3', verbose_name='Ενότητα 6 - Κείμενο'),
        ),
        migrations.AddField(
            model_name='dopsettings',
            name='section_7_label',
            field=models.TextField(default='7. Σε περίπτωση δήλωσης απόδοσης σχετικά με προϊόν του τομέα δομικών κατασκευών που καλύπτεται από εναρμονισμένο πρότυπο:', verbose_name='Ενότητα 7 - Τίτλος'),
        ),
        migrations.AddField(
            model_name='dopsettings',
            name='section_7_value',
            field=models.TextField(default='Βάσει του προτύπου EN 1279-5:2010, με σύμβαση sharing 22/2/2018', verbose_name='Ενότητα 7 - Κείμενο'),
        ),
        migrations.AddField(
            model_name='dopsettings',
            name='section_8_label',
            field=models.TextField(default='8. Σε περίπτωση δήλωσης απόδοσης σχετικά με προϊόν του τομέα δομικών κατασκευών για το οποίο έχει εκδοθεί ευρωπαϊκή τεχνική αξιολόγηση:', verbose_name='Ενότητα 8 - Τίτλος'),
        ),
        migrations.AddField(
            model_name='dopsettings',
            name='section_8_value',
            field=models.TextField(default='Δεν εφαρμόζεται', verbose_name='Ενότητα 8 - Κείμενο'),
        ),
    ]
