# Generated by Django 5.0.2 on 2026-07-25 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_dopsettings_section_texts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='En1279Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=30, unique=True, verbose_name='Αριθμός Εντύπου')),
                ('product_designation', models.CharField(max_length=255, verbose_name='Τύπος προϊόντος')),
                ('thermal_performance', models.CharField(max_length=100, verbose_name='Συντελεστής θερμοαγωγιμότητας (U)')),
                ('light_performance', models.CharField(max_length=100, verbose_name='Μετάδοση φωτός - αντανάκλαση φωτός')),
                ('energy_performance', models.CharField(max_length=100, verbose_name='Ηλιακός συντελεστής / Αντανάκλαση ενέργειας')),
                ('show_signature', models.BooleanField(default=True, verbose_name='Εμφάνιση Υπογραφής')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en1279_created', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
            ],
            options={
                'verbose_name': 'Έντυπο EN 1279-5',
                'verbose_name_plural': 'Έντυπα EN 1279-5',
                'ordering': ['-created_at'],
            },
        ),
    ]
