# Generated by Django 5.0.2 on 2026-07-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_en1279_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='En1279Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='documents/en1279/logo/', verbose_name='Λογότυπο')),
                ('logo_as_watermark', models.BooleanField(default=False, verbose_name='Υδατογράφημα')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='documents/en1279/signature/', verbose_name='Υπογραφή')),
                ('ce_mark', models.ImageField(blank=True, null=True, upload_to='documents/en1279/ce/', verbose_name='Σήμανση CE')),
                ('header_company_name', models.CharField(default='ΧΡΙΣΤΟΔΟΥΛΟΠΟΥΛΟΣ Γ. ΑΝΑΣΤΑΣΙΟΣ', max_length=200, verbose_name='Επωνυμία κεφαλίδας')),
                ('header_company_activity', models.CharField(default='ΕΠΕΞΕΡΓΑΣΙΑ - ΕΜΠΟΡΙΑ ΥΑΛΟΠΙΝΑΚΩΝ', max_length=200, verbose_name='Δραστηριότητα κεφαλίδας')),
                ('header_company_details', models.TextField(default='Ελ. Βενιζέλου 40, Αμαλιάδα\nΤηλ. 26220 28686 · Κιν. 6977 240040\nEmail: info@tasosxristodoulopoulosglass.gr\nΑΦΜ: 043758710 · ΔΟΥ: Αμαλιάδας', verbose_name='Στοιχεία κεφαλίδας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Τελευταία ενημέρωση')),
            ],
            options={
                'verbose_name': 'Ρυθμίσεις EN 1279-5',
                'verbose_name_plural': 'Ρυθμίσεις EN 1279-5',
            },
        ),
    ]
