# Generated by Django 5.0.2 on 2026-07-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_en1279_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='en1279settings',
            name='col_characteristic',
            field=models.CharField(default='ΙΔΙΟΤΗΤΑ / CHARACTERISTIC', max_length=120, verbose_name='Στήλη ιδιότητας'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='col_performance',
            field=models.CharField(default='ΑΠΟΔΟΣΗ / PERFORMANCE', max_length=120, verbose_name='Στήλη απόδοσης'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='col_spec',
            field=models.CharField(default='ΕΝΑΡΜΟΝΙΣΜΕΝΗ ΤΕΧΝΙΚΗ ΠΡΟΔΙΑΓΡΑΦΗ', max_length=120, verbose_name='Στήλη προδιαγραφής'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='col_units',
            field=models.CharField(default='ΜΟΝΑΔΕΣ', max_length=80, verbose_name='Στήλη μονάδων'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='designation_label',
            field=models.TextField(default='Τύπος προϊόντος: / Designation of product:', verbose_name='Τύπος προϊόντος - Τίτλος'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='npd_note',
            field=models.CharField(default='NPD-No performance determined', max_length=120, verbose_name='Σημείωση NPD'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='product_name_label',
            field=models.TextField(default='Περιγραφή του προϊόντος / Product name:', verbose_name='Περιγραφή προϊόντος - Τίτλος'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='product_name_value',
            field=models.TextField(default='Διπλοί μονωτικοί υαλοπίνακες που πρόκειται να χρησιμοποιηθούν σε κτίρια και κατασκευαστικά έργα / insulating glass unit, intended to be used in buildings and building works.', verbose_name='Περιγραφή προϊόντος - Κείμενο'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_10_characteristic',
            field=models.TextField(default='Μόνωση κατά απευθείας αερομεταφερόμενου θορύβου / Direct airborne sound reduction'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_10_performance',
            field=models.CharField(blank=True, default='npd', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_10_spec',
            field=models.CharField(default='EN 12758', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_10_units',
            field=models.CharField(default='dB', max_length=40),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_11_characteristic',
            field=models.TextField(default='Θερμικές ιδιότητες. Συντελεστής θερμοαγωγιμότητας / Thermal transmittance factor'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_11_spec',
            field=models.CharField(default='EN 673', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_11_units',
            field=models.CharField(default='U [W/M2k]', max_length=40),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_12_characteristic',
            field=models.TextField(default='Μετάδοση φωτός - αντανάκλαση φωτός / Light transmission- Light reflection'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_12_spec',
            field=models.CharField(default='EN 410', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_12_units',
            field=models.CharField(default='τv-ρv (%)', max_length=40),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_13_characteristic',
            field=models.TextField(default='Ηλιακός Συντελεστής / Αντανάκλαση ενέργειας / Energy solar factor / Energy reflection'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_13_spec',
            field=models.CharField(default='EN 410', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_13_units',
            field=models.CharField(default='g- pe (%)', max_length=40),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_1_characteristic',
            field=models.TextField(default='Αντίσταση στην φωτιά / Resistance to fire'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_1_performance',
            field=models.CharField(blank=True, default='npd', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_1_spec',
            field=models.CharField(default='EN-13501-2', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_1_units',
            field=models.CharField(default='Κλάση', max_length=40),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_2_characteristic',
            field=models.TextField(default='Αντίδραση στην φωτιά / Reaction to fire'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_2_performance',
            field=models.CharField(blank=True, default='npd', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_2_spec',
            field=models.CharField(default='EN-13501-1', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_2_units',
            field=models.CharField(default='Κλάση', max_length=40),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_3_characteristic',
            field=models.TextField(default='Αντίσταση σε εξωτερική φωτιά / Behaviour of external fire'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_3_performance',
            field=models.CharField(blank=True, default='npd', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_3_spec',
            field=models.CharField(default='EN 1279-5', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_3_units',
            field=models.CharField(default='Κλάση', max_length=40),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_4_characteristic',
            field=models.TextField(default='Αντίσταση σε σφαίρα / Bullet resistance'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_4_performance',
            field=models.CharField(blank=True, default='npd', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_4_spec',
            field=models.CharField(default='EN 1063', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_4_units',
            field=models.CharField(default='Κλάση', max_length=40),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_5_characteristic',
            field=models.TextField(default='Αντίσταση σε έκρηξη / Resistance to explosion'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_5_performance',
            field=models.CharField(blank=True, default='npd', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_5_spec',
            field=models.CharField(default='EN 13541', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_5_units',
            field=models.CharField(default='Κλάση', max_length=40),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_6_characteristic',
            field=models.TextField(default='Αντίσταση σε διάρρηξη / Resistance to hand attack'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_6_performance',
            field=models.CharField(blank=True, default='npd', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_6_spec',
            field=models.CharField(default='EN 356', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_6_units',
            field=models.CharField(default='Κλάση', max_length=40),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_7_characteristic',
            field=models.TextField(default='Αντίσταση σε κρούση εκκρεμών αντικειμένων / Resistance to pendulum impact'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_7_performance',
            field=models.CharField(blank=True, default='npd', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_7_spec',
            field=models.CharField(default='EN 12600', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_7_units',
            field=models.CharField(default='Κλάση', max_length=40),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_8_characteristic',
            field=models.TextField(default='Αντίσταση κατά ξαφνικών αλλαγών θερμοκρασίας και ανισοκατανομής θερμοκρασίας / Resistance to temperature differentials and temperature gradient'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_8_performance',
            field=models.CharField(blank=True, default='npd', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_8_spec',
            field=models.CharField(default='EN 572', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_8_units',
            field=models.CharField(default='[°K]', max_length=40),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_9_characteristic',
            field=models.TextField(default='Μόνιμη επιβαλλόμενη ανεμοπίεση, χιόνι, μόνιμα και/ή επιβαλλόμενα φορτία / Resistance to wind, snow, permanent and/or imposed load'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_9_performance',
            field=models.CharField(blank=True, default='npd', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_9_spec',
            field=models.CharField(default='EN 1279-5', max_length=80),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='row_9_units',
            field=models.CharField(default='mm', max_length=40),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='standard_code',
            field=models.CharField(default='EN 1279-5', max_length=50, verbose_name='Κωδικός προτύπου'),
        ),
        migrations.AddField(
            model_name='en1279settings',
            name='standard_intro',
            field=models.TextField(default='Σύμφωνα με τις απαιτήσεις του προτύπου / Under requirements of standart:', verbose_name='Κείμενο προτύπου'),
        ),
    ]
