# Generated by Django 5.0.2 on 2026-07-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_en1279_settings_row_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='En1279FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(choices=[('product_designation', 'Τύπος προϊόντος'), ('thermal_performance', 'Συντελεστής θερμοαγωγιμότητας U'), ('light_performance', 'Μετάδοση φωτός - αντανάκλαση φωτός'), ('energy_performance', 'Ηλιακός συντελεστής / Αντανάκλαση ενέργειας')], max_length=40, verbose_name='Πεδίο')),
                ('value', models.CharField(max_length=255, verbose_name='Τιμή')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Σειρά')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
            ],
            options={
                'verbose_name': 'Επιλογή πεδίου EN 1279-5',
                'verbose_name_plural': 'Επιλογές πεδίων EN 1279-5',
                'ordering': ['field_key', 'sort_order', 'value'],
            },
        ),
        migrations.AddConstraint(
            model_name='en1279fieldoption',
            constraint=models.UniqueConstraint(fields=('field_key', 'value'), name='uniq_en1279_field_option_value'),
        ),
    ]
