# Generated by Django 5.2 on 2025-08-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Επώνυμο')),
                ('first_name', models.CharField(max_length=100, verbose_name='Όνομα')),
                ('phone', models.CharField(max_length=20, verbose_name='Τηλέφωνο')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
            ],
            options={
                'verbose_name': 'Πελάτης',
                'verbose_name_plural': 'Πελάτες',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
