# Generated by Django 5.0.2 on 2026-07-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_customer_type_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name', 'company_name'], 'verbose_name': 'Πελάτης', 'verbose_name_plural': 'Πελάτες'},
        ),
    ]
