# Generated by Django 5.0.2 on 2026-07-01 08:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0023_warehouseuserprofile_is_managed_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Κωδικός')),
                ('name', models.CharField(max_length=200, verbose_name='Όνομα')),
                ('description', models.TextField(blank=True, default='', verbose_name='Περιγραφή')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
            ],
            options={
                'verbose_name': 'Προϊόν',
                'verbose_name_plural': 'Προϊόντα',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ποσότητα')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_usages', to='warehouse.product', verbose_name='Υλικό')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='products.finishedproduct', verbose_name='Προϊόν')),
            ],
            options={
                'verbose_name': 'Υλικό προϊόντος',
                'verbose_name_plural': 'Υλικά προϊόντος',
                'ordering': ['material__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='productmaterial',
            constraint=models.UniqueConstraint(fields=('product', 'material'), name='unique_product_material'),
        ),
    ]
