# Generated by Django 5.0.2 on 2026-07-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', verbose_name='Φωτογραφία'),
        ),
    ]
