# Generated by Django 5.0.2 on 2026-07-01 11:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_finishedproduct_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ποσότητα')),
                ('low_stock_threshold', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Όριο Χαμηλού Αποθέματος')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Προσθήκης')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.finishedproduct', verbose_name='Προϊόν')),
            ],
            options={
                'verbose_name': 'Απόθεμα Προϊόντος',
                'verbose_name_plural': 'Αποθέματα Προϊόντων',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('add', 'Προσθήκη'), ('remove', 'Αφαίρεση')], max_length=10, verbose_name='Τύπος')),
                ('amount', models.PositiveIntegerField(verbose_name='Ποσότητα')),
                ('quantity_before', models.IntegerField(verbose_name='Ποσότητα Πριν')),
                ('quantity_after', models.IntegerField(verbose_name='Ποσότητα Μετά')),
                ('note', models.TextField(blank=True, default='', verbose_name='Σημείωση')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Καταχωρήθηκε από')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.productstock', verbose_name='Απόθεμα προϊόντος')),
            ],
            options={
                'verbose_name': 'Κίνηση Αποθέματος Προϊόντος',
                'verbose_name_plural': 'Κινήσεις Αποθέματος Προϊόντων',
                'ordering': ['-created_at'],
            },
        ),
    ]
