# Generated by Django 5.0.2 on 2026-07-04 23:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_options'),
        ('products', '0003_productstock_productstockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_number', models.CharField(max_length=30, unique=True, verbose_name='Αριθμός Προσφοράς')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Σημείωση')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Σύνολο')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_created', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='customers.customer', verbose_name='Πελάτης')),
            ],
            options={
                'verbose_name': 'Προσφορά',
                'verbose_name_plural': 'Προσφορές',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ποσότητα')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Τιμή μονάδας')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.offer', verbose_name='Προσφορά')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_items', to='products.finishedproduct', verbose_name='Προϊόν')),
            ],
            options={
                'verbose_name': 'Γραμμή προσφοράς',
                'verbose_name_plural': 'Γραμμές προσφοράς',
                'ordering': ['id'],
            },
        ),
    ]
