# Generated by Django 5.0.2 on 2026-07-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productstock_variant_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstock',
            options={'ordering': ['product__name', 'construction_stage', 'carpet', 'bulb', 'dimensions'], 'verbose_name': 'Απόθεμα Προϊόντος', 'verbose_name_plural': 'Αποθέματα Προϊόντων'},
        ),
        migrations.AddField(
            model_name='productstock',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Δεσμευμένη ποσότητα'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='construction_stage',
            field=models.CharField(choices=[('skeleton', 'Σκελετός'), ('complete', 'Ολοκληρωμένο')], default='skeleton', max_length=20, verbose_name='Στάδιο Κατασκευής'),
        ),
    ]
